import 'package:flutter/material.dart';
import 'package:hive_flutter/hive_flutter.dart';
import 'app.dart';
import 'core/di/injection.dart';
import 'core/storage/local_storage.dart';
import 'features/notes/data/models/note_model.dart';
import 'features/onboarding/domain/usecases/check_onboarding_status.dart';
import 'helpers/logger.dart';

// Main entry point of the Flutter Clean App
//
// Initialization sequence:
// 1. Initialize Hive and SharedPreferences
// 2. Register Hive type adapters (auto-generated by build_runner)
// 3. Set up dependency injection
// 4. Check onboarding status
// 5. Launch app with appropriate initial route
void main() async {
  // Ensure Flutter binding is initialized
  WidgetsFlutterBinding.ensureInitialized();

  // Initialize Hive and SharedPreferences
  await LocalStorage.init();

  // Register Hive type adapters
  // IMPORTANT: NoteModelAdapter is auto-generated by running:
  //   flutter pub run build_runner build
  // This generates the 'note_model.g.dart' file from the @HiveType annotation
  Hive.registerAdapter(NoteModelAdapter());
  AppLogger.info('Hive type adapters registered');

  // Initialize dependency injection (GetIt)
  await initializeDependencies();
  AppLogger.info('Dependencies initialized');

  // Check if user has completed onboarding
  final checkOnboardingStatus = getIt<CheckOnboardingStatus>();
  final isOnboardingCompleted = await checkOnboardingStatus();
  AppLogger.info('Onboarding completed: $isOnboardingCompleted');

  // Run the app
  // - If onboarding completed → Navigate to Notes List
  // - If onboarding NOT completed → Show Onboarding screens
  runApp(MyApp(isOnboardingCompleted: isOnboardingCompleted));
}
